const std = @import("std");

pub const RawValue = struct {
    text: []const u8,
};

pub fn raw(comptime text: []const u8) RawValue {
    return .{ .text = text };
}

pub fn make(comptime macros: anytype) @TypeOf(macros) {
    @setEvalBranchQuota(10_000);
    validateMacroSet(@TypeOf(macros));
    return macros;
}

pub fn render(allocator: std.mem.Allocator, macros: anytype) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    const writer = out.writer(allocator);

    try writer.writeAll(
        "# AUTO-GENERATED BY embed-zig BK CONFIG\n" ++
            "# edit build.zig/build_config.zig; do not edit this file manually\n\n",
    );

    const MacroSet = @TypeOf(macros);
    inline for (@typeInfo(MacroSet).@"struct".fields) |field| {
        const value = @field(macros, field.name);
        try writeEntry(writer, field.name, value);
        try writer.writeByte('\n');
    }

    return out.toOwnedSlice(allocator);
}

fn writeEntry(writer: anytype, comptime name: []const u8, value: anytype) !void {
    const ValueType = @TypeOf(value);
    if (ValueType == RawValue) {
        try writer.print("CONFIG_{s}={s}", .{ name, value.text });
        return;
    }

    switch (@typeInfo(ValueType)) {
        .bool => {
            if (value) {
                try writer.print("CONFIG_{s}=y", .{name});
            } else {
                try writer.print("# CONFIG_{s} is not set", .{name});
            }
        },
        .int, .comptime_int => try writer.print("CONFIG_{s}={d}", .{ name, value }),
        .@"enum", .enum_literal => try writer.print("CONFIG_{s}={s}", .{ name, @tagName(value) }),
        .pointer, .array => {
            try writer.print("CONFIG_{s}=", .{name});
            try writeQuotedString(writer, value);
        },
        else => unreachable,
    }
}

fn writeQuotedString(writer: anytype, text: []const u8) !void {
    try writer.writeByte('"');
    for (text) |c| {
        switch (c) {
            '"' => try writer.writeAll("\\\""),
            '\\' => try writer.writeAll("\\\\"),
            else => try writer.writeByte(c),
        }
    }
    try writer.writeByte('"');
}

fn validateMacroSet(comptime MacroSet: type) void {
    switch (@typeInfo(MacroSet)) {
        .@"struct" => |info| {
            inline for (info.fields) |field| {
                validateName(field.name);
                validateValueType(field.type, field.name);
            }
        },
        else => @compileError("bk.armino.Config.make() expects a struct literal"),
    }
}

fn validateName(comptime name: []const u8) void {
    if (comptime name.len == 0) @compileError("config macro names must not be empty");
    if (comptime std.mem.startsWith(u8, name, "CONFIG_")) {
        @compileError("omit CONFIG_ prefix in bk.armino.Config.make()");
    }
    inline for (name) |c| {
        if (!((c >= 'A' and c <= 'Z') or (c >= 'a' and c <= 'z') or (c >= '0' and c <= '9') or c == '_')) {
            @compileError("config macro names must use only A-Z, a-z, 0-9, and _");
        }
    }
}

fn validateValueType(comptime ValueType: type, comptime name: []const u8) void {
    if (ValueType == RawValue) return;
    switch (@typeInfo(ValueType)) {
        .bool, .int, .comptime_int, .@"enum", .enum_literal => {},
        .pointer => |ptr| {
            if (ptr.size == .slice and ptr.child == u8) return;
            if (ptr.size == .one) {
                switch (@typeInfo(ptr.child)) {
                    .array => |array| if (array.child == u8) return,
                    else => {},
                }
            }
            @compileError(std.fmt.comptimePrint("unsupported config value type for {s}", .{name}));
        },
        .array => |array| {
            if (array.child == u8) return;
            @compileError(std.fmt.comptimePrint("unsupported config value type for {s}", .{name}));
        },
        else => @compileError(std.fmt.comptimePrint("unsupported config value type for {s}", .{name})),
    }
}
