const std = @import("std");

const Self = @This();

pub const PartitionType = enum {
    code,
    data,
};

pub const Side = enum {
    ap,
    cp,
};

pub const Size = union(enum) {
    raw: []const u8,
    bytes: u32,
    kb: u32,
    mb: u32,
};

pub const LittlefsOptions = struct {
    source_dir: []const u8,
    mount_path: []const u8 = "/littlefs",
    side: Side = .ap,
    block_size: u32 = 4096,
    page_size: u32 = 256,
};

pub const FlashdbKvOptions = struct {
    side: Side = .ap,
};

pub const Data = union(enum) {
    littlefs: LittlefsOptions,
    flashdb_kv: FlashdbKvOptions,
};

pub const data = struct {
    pub fn littlefs(options: LittlefsOptions) Data {
        return .{ .littlefs = options };
    }

    pub fn flashdbKv(options: FlashdbKvOptions) Data {
        return .{ .flashdb_kv = options };
    }
};

pub const Partition = struct {
    name: []const u8,
    offset: ?u32 = null,
    size: Size,
    kind: PartitionType,
    read: bool,
    write: bool,
    data: ?Data = null,
};

entries: []const Partition,

pub const Options = struct {
    entries: []const Partition,
};

pub fn make(options: Options) Self {
    return .{
        .entries = options.entries,
    };
}

pub fn rawSize(text: []const u8) Size {
    return .{ .raw = text };
}

pub fn kb(value: u32) Size {
    return .{ .kb = value };
}

pub fn mb(value: u32) Size {
    return .{ .mb = value };
}

pub fn bytes(value: u32) Size {
    return .{ .bytes = value };
}

pub fn renderCsv(allocator: std.mem.Allocator, table: Self) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    const writer = out.writer(allocator);

    try writer.writeAll(
        "# AUTO-GENERATED BY embed-zig BK PARTITION GENERATOR\n" ++
            "# edit build.zig/build_config.zig; do not edit this file manually\n" ++
            "# The bin size whose type is code occupies more space in flash,,,,,\n" ++
            "# The occupied space is: bin size*34/32(and 68K aligned),,,,,\n" ++
            "# easyflash:beken CP some components use it\n" ++
            "# easyflash_ap:beken AP some components use it\n" ++
            "#Name,Offset,Size,Type,Read,Write\n",
    );

    for (table.entries) |entry| {
        try writer.print("{s},", .{entry.name});
        if (entry.offset) |offset| {
            try writer.print("0x{x}", .{offset});
        }
        try writer.writeByte(',');
        try writeSize(writer, entry.size);
        try writer.print(",{s},{s},{s}\n", .{
            @tagName(entry.kind),
            boolText(entry.read),
            boolText(entry.write),
        });
    }

    return out.toOwnedSlice(allocator);
}

pub fn renderDerivedConfig(allocator: std.mem.Allocator, table: Self, side: Side) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    const writer = out.writer(allocator);

    var has_littlefs = false;
    var flashdb_kv: ?Partition = null;

    for (table.entries) |entry| {
        const entry_data = entry.data orelse continue;
        switch (entry_data) {
            .littlefs => |options| {
                if (options.side == side) has_littlefs = true;
            },
            .flashdb_kv => |options| {
                if (options.side != side) continue;
                if (side != .ap) {
                    @panic("BK FlashDB is currently supported only for AP");
                }
                if (flashdb_kv != null) {
                    @panic("BK FlashDB KVDB supports only one generated KVDB partition");
                }
                flashdb_kv = entry;
            },
        }
    }

    if (has_littlefs) {
        try writer.writeAll(
            "\n# Derived from bk.armino.PartitionTable.data.littlefs\n" ++
                "CONFIG_LITTLEFS=y\n" ++
                "CONFIG_LITTLEFS_USE_LITTLEFS_PARTITION=y\n" ++
                "# CONFIG_LITTLEFS_USE_USR_CONFIG_PARTITION is not set\n" ++
                "# CONFIG_LITTLEFS_NO_CONFIG_PARTITION is not set\n" ++
                "CONFIG_VFS=y\n",
        );
    }

    if (flashdb_kv) |entry| {
        const offset = entry.offset orelse {
            @panic("BK FlashDB KVDB partition must set an explicit .offset");
        };
        const size = sizeBytes(entry.size) catch {
            @panic("BK FlashDB KVDB partition must use a numeric size or a parseable raw size");
        };
        try writer.print(
            "\n# Derived from bk.armino.PartitionTable.data.flashdbKv\n" ++
                "CONFIG_FLASHDB=y\n" ++
                "CONFIG_FLASHDB_USING_KVDB=y\n" ++
                "CONFIG_FLASHDB_KVDB_START_ADDR=0x{x}\n" ++
                "CONFIG_FLASHDB_KVDB_SIZE=0x{x}\n",
            .{ offset, size },
        );
    }

    return out.toOwnedSlice(allocator);
}

pub fn sizeBytes(size: Size) !u32 {
    return switch (size) {
        .bytes => |value| value,
        .kb => |value| std.math.mul(u32, value, 1024),
        .mb => |value| std.math.mul(u32, value, 1024 * 1024),
        .raw => |text| parseRawSize(text),
    };
}

fn writeSize(writer: anytype, size: Size) !void {
    switch (size) {
        .raw => |text| try writer.writeAll(text),
        .bytes => |value| try writer.print("{d}", .{value}),
        .kb => |value| try writer.print("{d}K", .{value}),
        .mb => |value| try writer.print("{d}M", .{value}),
    }
}

fn parseRawSize(text: []const u8) !u32 {
    if (text.len == 0) return error.InvalidSize;

    var number = text;
    var multiplier: u32 = 1;
    const suffix = text[text.len - 1];
    if (suffix == 'k' or suffix == 'K') {
        number = text[0 .. text.len - 1];
        multiplier = 1024;
    } else if (suffix == 'm' or suffix == 'M') {
        number = text[0 .. text.len - 1];
        multiplier = 1024 * 1024;
    }

    const value = if (std.mem.startsWith(u8, number, "0x") or std.mem.startsWith(u8, number, "0X"))
        try std.fmt.parseUnsigned(u32, number[2..], 16)
    else
        try std.fmt.parseUnsigned(u32, number, 10);
    return std.math.mul(u32, value, multiplier);
}

fn boolText(value: bool) []const u8 {
    return if (value) "TRUE" else "FALSE";
}
