const std = @import("std");

const Self = @This();

pub const MemoryType = enum {
    SRAM,
    PSRAM,
};

pub const Size = union(enum) {
    raw: []const u8,
    bytes: u32,
};

pub const Region = struct {
    name: []const u8,
    kind: MemoryType,
    offset: ?u32 = null,
    size: Size,
};

psram_capacity_size: []const u8,
regions: []const Region,

pub const Options = struct {
    psram_capacity_size: []const u8 = "8M",
    regions: []const Region,
};

pub fn make(options: Options) Self {
    return .{
        .psram_capacity_size = options.psram_capacity_size,
        .regions = options.regions,
    };
}

pub fn rawSize(text: []const u8) Size {
    return .{ .raw = text };
}

pub fn bytes(value: u32) Size {
    return .{ .bytes = value };
}

pub fn renderCsv(allocator: std.mem.Allocator, table: Self) ![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);
    const writer = out.writer(allocator);

    try writer.writeAll(
        "# AUTO-GENERATED BY embed-zig BK RAM REGION GENERATOR\n" ++
            "# edit build.zig/build_config.zig; do not edit this file manually\n" ++
            "# please read doc: https://docs.bekencorp.com/arminodoc/bk_avdk_smp/smp_doc/bk7258/zh_CN/v3.1.1/developer-guide/config_tools/bk_config_ram_regions.html\n" ++
            "# SRAM base addr is 0x28000000, capacity is 640K\n" ++
            "# PSRAM base addr is 0x60000000\n",
    );
    try writer.print("PSRAM_CAPCAITY_SIZE={s}\n", .{table.psram_capacity_size});
    try writer.writeAll("#Name,Type,Offset,Size\n");

    for (table.regions) |region| {
        try writer.print("{s},{s},", .{ region.name, @tagName(region.kind) });
        if (region.offset) |offset| {
            try writer.print("0x{x:0>8}", .{offset});
        }
        try writer.writeByte(',');
        try writeSize(writer, region.size);
        try writer.writeByte('\n');
    }

    return out.toOwnedSlice(allocator);
}

fn writeSize(writer: anytype, size: Size) !void {
    switch (size) {
        .raw => |text| try writer.writeAll(text),
        .bytes => |value| try writer.print("0x{x:0>6}", .{value}),
    }
}
