const embed_core = @import("embed_core");

pub const std = @import("esp").grt.std;
pub const audio = embed_core.audio;
pub const board = embed_core.board;
pub const bt = @import("embed/bt.zig");
pub const drivers = embed_core.drivers;
pub const ledstrip = embed_core.ledstrip;
pub const motion = embed_core.motion;
pub const system = @import("embed/system.zig");
pub const zux = embed_core.zux;
pub const audio_adapter = @import("embed/audio.zig");
pub const BtHost = @import("embed/BtHost.zig");
pub const HostedCopro = @import("embed/HostedCopro.zig");
pub const display = @import("embed/display.zig");
pub const I2c = @import("embed/I2c.zig");
pub const time = @import("embed/time.zig");
pub const wifi = @import("embed/Wifi.zig");
pub const boards = @import("embed/boards.zig");
