const std = @import("std");

const c = @cImport({
    @cInclude("lvgl.h");
    @cInclude("lv_os_custom.h");
    @cInclude("src/osal/lv_os.h");
});

pub const Result = c.lv_result_t;
pub const Opa = c.lv_opa_t;
pub const StyleProp = c.lv_style_prop_t;
pub const StyleValue = c.lv_style_value_t;
pub const StyleRes = c.lv_style_res_t;

pub const Color = c.lv_color_t;
pub const Color32 = c.lv_color32_t;
pub const ColorHsv = c.lv_color_hsv_t;
pub const ColorFormat = c.lv_color_format_t;
pub const DisplayRenderMode = c.lv_display_render_mode_t;

pub const Point = c.lv_point_t;
pub const PointPrecise = c.lv_point_precise_t;
pub const Area = c.lv_area_t;
pub const Align = c.lv_align_t;
pub const Dir = c.lv_dir_t;

pub const Style = c.lv_style_t;
pub const StyleSelector = c.lv_style_selector_t;
pub const Display = c.lv_display_t;
pub const DisplayRotation = c.lv_display_rotation_t;
pub const Indev = c.lv_indev_t;
pub const IndevType = c.lv_indev_type_t;
pub const IndevState = c.lv_indev_state_t;
pub const IndevMode = c.lv_indev_mode_t;
pub const IndevData = c.lv_indev_data_t;
pub const IndevReadCb = c.lv_indev_read_cb_t;
pub const IndevKeyRemapCb = c.lv_indev_key_remap_cb_t;
pub const Group = c.lv_group_t;
pub const Key = c.lv_key_t;
pub const Obj = c.lv_obj_t;
pub const ObjFlag = c.lv_obj_flag_t;
pub const State = c.lv_state_t;
pub const Part = c.lv_part_t;
pub const LabelLongMode = c.lv_label_long_mode_t;
pub const Event = c.lv_event_t;
pub const EventDsc = c.lv_event_dsc_t;
pub const EventCallback = c.lv_event_cb_t;
pub const EventCode = c.lv_event_code_t;
pub const Anim = c.lv_anim_t;
pub const Timer = c.lv_timer_t;
pub const AnimExecXcb = c.lv_anim_exec_xcb_t;
pub const TickGetCb = c.lv_tick_get_cb_t;
pub const DelayCb = c.lv_delay_cb_t;
pub const Mutex = c.lv_mutex_t;
pub const Thread = c.lv_thread_t;
pub const ThreadSync = c.lv_thread_sync_t;
pub const ThreadPrio = c_int;
pub const ThreadCallback = *const fn (?*anyopaque) callconv(.c) void;
pub const Subject = c.lv_subject_t;
pub const SubjectType = c.lv_subject_type_t;
pub const SubjectValue = c.lv_subject_value_t;
pub const Observer = c.lv_observer_t;

pub const LV_COLOR_DEPTH = c.LV_COLOR_DEPTH;
pub const LV_RESULT_OK: Result = @intCast(c.LV_RESULT_OK);
pub const LV_RESULT_INVALID: Result = @intCast(c.LV_RESULT_INVALID);
pub const LV_COLOR_FORMAT_RGB565 = c.LV_COLOR_FORMAT_RGB565;
pub const LV_NO_TIMER_READY = c.LV_NO_TIMER_READY;
pub const LV_ANIM_REPEAT_INFINITE = c.LV_ANIM_REPEAT_INFINITE;
pub const LV_ANIM_PLAYTIME_INFINITE = c.LV_ANIM_PLAYTIME_INFINITE;
pub const LV_ANIM_PAUSE_FOREVER = c.LV_ANIM_PAUSE_FOREVER;
pub const LV_DISPLAY_RENDER_MODE_PARTIAL = c.LV_DISPLAY_RENDER_MODE_PARTIAL;
pub const LV_DISPLAY_RENDER_MODE_DIRECT = c.LV_DISPLAY_RENDER_MODE_DIRECT;
pub const LV_DISPLAY_RENDER_MODE_FULL = c.LV_DISPLAY_RENDER_MODE_FULL;
pub const LV_STYLE_WIDTH = c.LV_STYLE_WIDTH;
pub const LV_PART_MAIN = c.LV_PART_MAIN;
pub const LV_PART_ANY = c.LV_PART_ANY;
pub const LV_STATE_DEFAULT = c.LV_STATE_DEFAULT;
pub const LV_STATE_PRESSED = c.LV_STATE_PRESSED;
pub const LV_STATE_FOCUSED = c.LV_STATE_FOCUSED;
pub const LV_STATE_DISABLED = c.LV_STATE_DISABLED;
pub const LV_STATE_CHECKED = c.LV_STATE_CHECKED;
pub const LV_STATE_USER_4 = c.LV_STATE_USER_4;
pub const LV_STATE_ANY = c.LV_STATE_ANY;
pub const LV_OBJ_FLAG_HIDDEN = c.LV_OBJ_FLAG_HIDDEN;
pub const LV_OBJ_FLAG_CLICKABLE = c.LV_OBJ_FLAG_CLICKABLE;
pub const LV_OBJ_FLAG_SCROLLABLE = c.LV_OBJ_FLAG_SCROLLABLE;
pub const LV_OBJ_FLAG_EVENT_BUBBLE = c.LV_OBJ_FLAG_EVENT_BUBBLE;
pub const LV_OBJ_FLAG_EVENT_TRICKLE = c.LV_OBJ_FLAG_EVENT_TRICKLE;
pub const LV_LABEL_LONG_MODE_WRAP = c.LV_LABEL_LONG_MODE_WRAP;
pub const LV_LABEL_LONG_MODE_DOTS = c.LV_LABEL_LONG_MODE_DOTS;
pub const LV_LABEL_LONG_MODE_SCROLL = c.LV_LABEL_LONG_MODE_SCROLL;
pub const LV_LABEL_LONG_MODE_SCROLL_CIRCULAR = c.LV_LABEL_LONG_MODE_SCROLL_CIRCULAR;
pub const LV_LABEL_LONG_MODE_CLIP = c.LV_LABEL_LONG_MODE_CLIP;

pub const lv_init = c.lv_init;
pub const lv_deinit = c.lv_deinit;
pub const lv_is_initialized = c.lv_is_initialized;
pub extern fn lv_lock() void;
pub extern fn lv_lock_isr() Result;
pub extern fn lv_unlock() void;
pub extern fn lv_thread_init(thread: ?*Thread, name: ?[*:0]const u8, prio: ThreadPrio, callback: ?ThreadCallback, stack_size: usize, user_data: ?*anyopaque) Result;
pub extern fn lv_thread_delete(thread: ?*Thread) Result;
pub extern fn lv_mutex_init(mutex: ?*Mutex) Result;
pub extern fn lv_mutex_lock(mutex: ?*Mutex) Result;
pub extern fn lv_mutex_lock_isr(mutex: ?*Mutex) Result;
pub extern fn lv_mutex_unlock(mutex: ?*Mutex) Result;
pub extern fn lv_mutex_delete(mutex: ?*Mutex) Result;
pub extern fn lv_thread_sync_init(sync: ?*ThreadSync) Result;
pub extern fn lv_thread_sync_wait(sync: ?*ThreadSync) Result;
pub extern fn lv_thread_sync_signal(sync: ?*ThreadSync) Result;
pub extern fn lv_thread_sync_signal_isr(sync: ?*ThreadSync) Result;
pub extern fn lv_thread_sync_delete(sync: ?*ThreadSync) Result;

pub const lv_point_set = c.lv_point_set;
pub const lv_point_swap = c.lv_point_swap;

pub const lv_area_set = c.lv_area_set;
pub const lv_area_get_width = c.lv_area_get_width;
pub const lv_area_get_height = c.lv_area_get_height;
pub const lv_area_set_width = c.lv_area_set_width;
pub const lv_area_set_height = c.lv_area_set_height;
pub const lv_area_get_size = c.lv_area_get_size;
pub const lv_area_increase = c.lv_area_increase;
pub const lv_area_move = c.lv_area_move;

pub const lv_color_format_get_bpp = c.lv_color_format_get_bpp;
pub const lv_color_format_get_size = c.lv_color_format_get_size;
pub const lv_color_format_has_alpha = c.lv_color_format_has_alpha;
pub const lv_color_to_32 = c.lv_color_to_32;
pub const lv_color_to_int = c.lv_color_to_int;
pub const lv_color_eq = c.lv_color_eq;
pub const lv_color_hex = c.lv_color_hex;
pub const lv_color_make = c.lv_color_make;
pub const lv_color_hex3 = c.lv_color_hex3;
pub const lv_color_lighten = c.lv_color_lighten;
pub const lv_color_darken = c.lv_color_darken;
pub const lv_color_hsv_to_rgb = c.lv_color_hsv_to_rgb;
pub const lv_color_to_hsv = c.lv_color_to_hsv;
pub const lv_color_white = c.lv_color_white;
pub const lv_color_black = c.lv_color_black;
pub const lv_color_luminance = c.lv_color_luminance;

pub const lv_style_init = c.lv_style_init;
pub const lv_style_reset = c.lv_style_reset;
pub const lv_style_copy = c.lv_style_copy;
pub const lv_style_merge = c.lv_style_merge;
pub const lv_style_get_num_custom_props = c.lv_style_get_num_custom_props;
pub const lv_style_remove_prop = c.lv_style_remove_prop;
pub const lv_style_set_prop = c.lv_style_set_prop;
pub const lv_style_get_prop = c.lv_style_get_prop;
pub const lv_style_is_empty = c.lv_style_is_empty;
pub const lv_style_set_width = c.lv_style_set_width;

pub const lv_display_create = c.lv_display_create;
pub const lv_display_delete = c.lv_display_delete;
pub const lv_display_set_default = c.lv_display_set_default;
pub const lv_display_get_default = c.lv_display_get_default;
pub const lv_display_get_screen_active = c.lv_display_get_screen_active;
pub const lv_display_set_resolution = c.lv_display_set_resolution;
pub const lv_display_set_physical_resolution = c.lv_display_set_physical_resolution;
pub const lv_display_set_offset = c.lv_display_set_offset;
pub const lv_display_set_rotation = c.lv_display_set_rotation;
pub const lv_display_set_dpi = c.lv_display_set_dpi;
pub const lv_display_set_buffers = c.lv_display_set_buffers;
pub const lv_display_set_flush_cb = c.lv_display_set_flush_cb;
pub const lv_display_set_color_format = c.lv_display_set_color_format;
pub const lv_display_flush_ready = c.lv_display_flush_ready;
pub const lv_display_set_user_data = c.lv_display_set_user_data;
pub const lv_display_get_user_data = c.lv_display_get_user_data;
pub const lv_display_get_horizontal_resolution = c.lv_display_get_horizontal_resolution;
pub const lv_display_get_vertical_resolution = c.lv_display_get_vertical_resolution;
pub const lv_display_get_original_horizontal_resolution = c.lv_display_get_original_horizontal_resolution;
pub const lv_display_get_original_vertical_resolution = c.lv_display_get_original_vertical_resolution;
pub const lv_display_get_physical_horizontal_resolution = c.lv_display_get_physical_horizontal_resolution;
pub const lv_display_get_physical_vertical_resolution = c.lv_display_get_physical_vertical_resolution;
pub const lv_display_get_offset_x = c.lv_display_get_offset_x;
pub const lv_display_get_offset_y = c.lv_display_get_offset_y;
pub const lv_display_get_rotation = c.lv_display_get_rotation;
pub const lv_display_get_dpi = c.lv_display_get_dpi;

pub const lv_indev_create = c.lv_indev_create;
pub const lv_indev_delete = c.lv_indev_delete;
pub const lv_indev_get_next = c.lv_indev_get_next;
pub const lv_indev_read = c.lv_indev_read;
pub const lv_indev_enable = c.lv_indev_enable;
pub const lv_indev_active = c.lv_indev_active;
pub const lv_indev_set_type = c.lv_indev_set_type;
pub const lv_indev_get_type = c.lv_indev_get_type;
pub const lv_indev_set_read_cb = c.lv_indev_set_read_cb;
pub const lv_indev_get_read_cb = c.lv_indev_get_read_cb;
pub const lv_indev_set_user_data = c.lv_indev_set_user_data;
pub const lv_indev_get_user_data = c.lv_indev_get_user_data;
pub const lv_indev_set_driver_data = c.lv_indev_set_driver_data;
pub const lv_indev_get_driver_data = c.lv_indev_get_driver_data;
pub const lv_indev_set_display = c.lv_indev_set_display;
pub const lv_indev_get_display = c.lv_indev_get_display;
pub const lv_indev_set_long_press_time = c.lv_indev_set_long_press_time;
pub const lv_indev_set_long_press_repeat_time = c.lv_indev_set_long_press_repeat_time;
pub const lv_indev_set_scroll_limit = c.lv_indev_set_scroll_limit;
pub const lv_indev_set_scroll_throw = c.lv_indev_set_scroll_throw;
pub const lv_indev_reset = c.lv_indev_reset;
pub const lv_indev_reset_long_press = c.lv_indev_reset_long_press;
pub const lv_indev_stop_processing = c.lv_indev_stop_processing;
pub const lv_indev_set_cursor = c.lv_indev_set_cursor;
pub const lv_indev_set_group = c.lv_indev_set_group;
pub const lv_indev_get_group = c.lv_indev_get_group;
pub const lv_indev_set_button_points = c.lv_indev_set_button_points;
pub const lv_indev_get_point = c.lv_indev_get_point;
pub const lv_indev_get_key = c.lv_indev_get_key;
pub const lv_indev_get_scroll_dir = c.lv_indev_get_scroll_dir;
pub const lv_indev_get_scroll_obj = c.lv_indev_get_scroll_obj;
pub const lv_indev_get_vect = c.lv_indev_get_vect;
pub const lv_indev_get_cursor = c.lv_indev_get_cursor;
pub const lv_indev_wait_release = c.lv_indev_wait_release;
pub const lv_indev_get_active_obj = c.lv_indev_get_active_obj;
pub const lv_indev_get_read_timer = c.lv_indev_get_read_timer;
pub const lv_indev_set_mode = c.lv_indev_set_mode;
pub const lv_indev_get_mode = c.lv_indev_get_mode;
pub const lv_indev_search_obj = c.lv_indev_search_obj;
pub const lv_indev_add_event_cb = c.lv_indev_add_event_cb;
pub const lv_indev_get_event_count = c.lv_indev_get_event_count;
pub const lv_indev_get_event_dsc = c.lv_indev_get_event_dsc;
pub const lv_indev_remove_event = c.lv_indev_remove_event;
pub const lv_indev_remove_event_cb_with_user_data = c.lv_indev_remove_event_cb_with_user_data;
pub const lv_indev_send_event = c.lv_indev_send_event;
pub const lv_indev_set_key_remap_cb = c.lv_indev_set_key_remap_cb;

pub const lv_obj_create = c.lv_obj_create;
pub const lv_obj_delete = c.lv_obj_delete;
pub const lv_obj_clean = c.lv_obj_clean;
pub const lv_obj_set_parent = c.lv_obj_set_parent;
pub const lv_obj_get_screen = c.lv_obj_get_screen;
pub const lv_obj_get_display = c.lv_obj_get_display;
pub const lv_obj_get_parent = c.lv_obj_get_parent;
pub const lv_obj_get_child = c.lv_obj_get_child;
pub const lv_obj_get_child_count = c.lv_obj_get_child_count;
pub const lv_obj_set_pos = c.lv_obj_set_pos;
pub const lv_obj_set_x = c.lv_obj_set_x;
pub const lv_obj_set_y = c.lv_obj_set_y;
pub const lv_obj_set_size = c.lv_obj_set_size;
pub const lv_obj_set_width = c.lv_obj_set_width;
pub const lv_obj_set_height = c.lv_obj_set_height;
pub const lv_obj_update_layout = c.lv_obj_update_layout;
pub const lv_obj_get_x = c.lv_obj_get_x;
pub const lv_obj_get_y = c.lv_obj_get_y;
pub const lv_obj_get_width = c.lv_obj_get_width;
pub const lv_obj_get_height = c.lv_obj_get_height;
pub const lv_obj_add_flag = c.lv_obj_add_flag;
pub const lv_obj_remove_flag = c.lv_obj_remove_flag;
pub const lv_obj_set_flag = c.lv_obj_set_flag;
pub const lv_obj_has_flag = c.lv_obj_has_flag;
pub const lv_obj_has_flag_any = c.lv_obj_has_flag_any;
pub const lv_obj_add_state = c.lv_obj_add_state;
pub const lv_obj_remove_state = c.lv_obj_remove_state;
pub const lv_obj_set_state = c.lv_obj_set_state;
pub const lv_obj_get_state = c.lv_obj_get_state;
pub const lv_obj_has_state = c.lv_obj_has_state;
pub const lv_obj_add_style = c.lv_obj_add_style;
pub const lv_obj_remove_style = c.lv_obj_remove_style;
pub const lv_obj_remove_style_all = c.lv_obj_remove_style_all;
pub const lv_obj_refresh_style = c.lv_obj_refresh_style;
pub const lv_obj_get_style_prop = c.lv_obj_get_style_prop;
pub const lv_obj_has_style_prop = c.lv_obj_has_style_prop;
pub const lv_obj_send_event = c.lv_obj_send_event;
pub const lv_obj_add_event_cb = c.lv_obj_add_event_cb;
pub const lv_obj_get_event_count = c.lv_obj_get_event_count;
pub const lv_obj_remove_event_dsc = c.lv_obj_remove_event_dsc;
pub const lv_screen_active = c.lv_screen_active;
pub const lv_refr_now = c.lv_refr_now;
pub const lv_timer_handler = c.lv_timer_handler;

pub const lv_tick_inc = c.lv_tick_inc;
pub const lv_tick_get = c.lv_tick_get;
pub const lv_tick_elaps = c.lv_tick_elaps;
pub const lv_tick_diff = c.lv_tick_diff;
pub const lv_delay_ms = c.lv_delay_ms;
pub const lv_delay_set_cb = c.lv_delay_set_cb;
pub const lv_tick_set_cb = c.lv_tick_set_cb;
pub const lv_tick_get_cb = c.lv_tick_get_cb;

pub const lv_label_create = c.lv_label_create;
pub const lv_label_set_text = c.lv_label_set_text;
pub const lv_label_set_text_static = c.lv_label_set_text_static;
pub const lv_label_get_text = c.lv_label_get_text;
pub const lv_label_set_long_mode = c.lv_label_set_long_mode;
pub const lv_label_get_long_mode = c.lv_label_get_long_mode;
pub const lv_button_create = c.lv_button_create;

pub const lv_event_get_target = c.lv_event_get_target;
pub const lv_event_get_current_target = c.lv_event_get_current_target;
pub const lv_event_get_target_obj = c.lv_event_get_target_obj;
pub const lv_event_get_current_target_obj = c.lv_event_get_current_target_obj;
pub const lv_event_get_code = c.lv_event_get_code;
pub const lv_event_get_param = c.lv_event_get_param;
pub const lv_event_get_user_data = c.lv_event_get_user_data;
pub const lv_event_stop_bubbling = c.lv_event_stop_bubbling;
pub const lv_event_stop_trickling = c.lv_event_stop_trickling;
pub const lv_event_stop_processing = c.lv_event_stop_processing;
pub const lv_event_register_id = c.lv_event_register_id;
pub const lv_event_code_get_name = c.lv_event_code_get_name;

pub const lv_anim_init = c.lv_anim_init;
pub const lv_anim_set_var = c.lv_anim_set_var;
pub const lv_anim_set_duration = c.lv_anim_set_duration;
pub const lv_anim_set_delay = c.lv_anim_set_delay;
pub const lv_anim_resume = c.lv_anim_resume;
pub const lv_anim_pause = c.lv_anim_pause;
pub const lv_anim_pause_for = c.lv_anim_pause_for;
pub const lv_anim_is_paused = c.lv_anim_is_paused;
pub const lv_anim_set_values = c.lv_anim_set_values;
pub const lv_anim_set_reverse_duration = c.lv_anim_set_reverse_duration;
pub const lv_anim_set_reverse_delay = c.lv_anim_set_reverse_delay;
pub const lv_anim_set_repeat_count = c.lv_anim_set_repeat_count;
pub const lv_anim_set_repeat_delay = c.lv_anim_set_repeat_delay;
pub const lv_anim_set_early_apply = c.lv_anim_set_early_apply;
pub const lv_anim_set_exec_cb = c.lv_anim_set_exec_cb;
pub const lv_anim_start = c.lv_anim_start;
pub const lv_anim_delete_all = c.lv_anim_delete_all;
pub extern fn embed_lv_anim_create() ?*Anim;
pub extern fn embed_lv_anim_destroy(anim: *Anim) void;
pub extern fn embed_lv_anim_get_start_value(anim: *const Anim) i32;
pub extern fn embed_lv_anim_get_end_value(anim: *const Anim) i32;
pub extern fn embed_lv_anim_get_duration(anim: *const Anim) i32;
pub extern fn embed_lv_anim_get_act_time(anim: *const Anim) i32;
pub extern fn embed_lv_anim_get_reverse_delay(anim: *const Anim) u32;
pub extern fn embed_lv_anim_get_reverse_duration(anim: *const Anim) u32;
pub extern fn embed_lv_anim_get_repeat_delay(anim: *const Anim) u32;
pub extern fn embed_lv_anim_get_repeat_count(anim: *const Anim) u32;
pub extern fn embed_lv_anim_get_early_apply(anim: *const Anim) u8;

pub const lv_subject_init_int = c.lv_subject_init_int;
pub const lv_subject_set_int = c.lv_subject_set_int;
pub const lv_subject_get_int = c.lv_subject_get_int;
pub const lv_subject_get_previous_int = c.lv_subject_get_previous_int;
pub const lv_subject_set_min_value_int = c.lv_subject_set_min_value_int;
pub const lv_subject_set_max_value_int = c.lv_subject_set_max_value_int;
pub const lv_subject_init_pointer = c.lv_subject_init_pointer;
pub const lv_subject_set_pointer = c.lv_subject_set_pointer;
pub const lv_subject_get_pointer = c.lv_subject_get_pointer;
pub const lv_subject_get_previous_pointer = c.lv_subject_get_previous_pointer;
pub const lv_subject_init_string = c.lv_subject_init_string;
pub const lv_subject_copy_string = c.lv_subject_copy_string;
pub const lv_subject_get_string = c.lv_subject_get_string;
pub const lv_subject_get_previous_string = c.lv_subject_get_previous_string;
pub const lv_subject_deinit = c.lv_subject_deinit;
pub const lv_subject_add_observer = c.lv_subject_add_observer;
pub extern fn embed_lv_subject_create() ?*Subject;
pub extern fn embed_lv_subject_destroy(subject: *Subject) void;
pub const lv_observer_remove = c.lv_observer_remove;
pub const lv_observer_get_target = c.lv_observer_get_target;
pub const lv_observer_get_target_obj = c.lv_observer_get_target_obj;
pub const lv_observer_get_user_data = c.lv_observer_get_user_data;

test "lvgl/unit_tests/binding/exports_lvgl_base_symbols" {
    const testing = std.testing;

    try testing.expect(@sizeOf(Color) > 0);
    try testing.expect(@sizeOf(Point) > 0);
    try testing.expect(@sizeOf(Area) > 0);
    try testing.expect(@sizeOf(Style) > 0);
    try testing.expect(@typeInfo(Anim) == .@"opaque");
    try testing.expect(@typeInfo(Subject) == .@"opaque");

    try testing.expect(LV_COLOR_DEPTH > 0);
    try testing.expect(LV_PART_ANY != 0);
    try testing.expect(LV_STATE_ANY != 0);
    try testing.expect(LV_OBJ_FLAG_CLICKABLE != 0);

    _ = lv_color_make;
    _ = lv_area_get_width;
    _ = lv_style_init;
    _ = lv_style_set_width;
    _ = lv_display_create;
    _ = lv_display_get_screen_active;
    _ = lv_indev_create;
    _ = lv_indev_set_read_cb;
    _ = lv_indev_set_display;
    _ = lv_tick_inc;
    _ = lv_tick_get;
    _ = lv_lock;
    _ = lv_thread_init;
    _ = lv_mutex_init;
    _ = lv_thread_sync_init;
    _ = lv_anim_set_exec_cb;
    _ = lv_obj_create;
    _ = lv_obj_get_child_count;
    _ = lv_obj_add_event_cb;
    _ = lv_label_create;
    _ = lv_label_get_text;
    _ = lv_button_create;
    _ = lv_event_get_code;
    _ = lv_event_get_target_obj;
    _ = lv_anim_init;
    _ = lv_subject_init_int;
    _ = embed_lv_anim_create;
    _ = embed_lv_subject_create;
}
