const std = @import("std");
const schema = @import("partition_table/schema.zig");
const default_partition = @import("partition_table/default.zig");

const Self = @This();

pub const PartitionType = schema.PartitionType;
pub const PartitionSubtype = schema.PartitionSubtype;
pub const Partition = schema.Partition;
pub const DataSource = schema.DataSource;
pub const data = schema.data;
pub const NvsEntry = schema.NvsEntry;
pub const NvsData = schema.NvsData;
pub const NvsValue = schema.NvsValue;
pub const NvsValueType = schema.NvsValueType;

offset: u32,
entries: []const Partition,

pub const default_table: Self = .{
    .offset = default_partition.table.offset,
    .entries = default_partition.table.entries,
};
pub const default_offset = default_table.offset;

pub const Options = struct {
    offset: u32 = default_offset,
    entries: []const Partition = default_table.entries,
};

pub const ResolvedPartition = struct {
    name: []const u8,
    kind: PartitionType,
    subtype: PartitionSubtype,
    offset: u32,
    size: u32,
    flags: ?[]const u8 = null,
    data: ?DataSource = null,
};

pub const ValidateError = error{
    MissingAppPartition,
    InvalidAppPartitionSubtype,
    InvalidDataPartitionSubtype,
};

pub fn make(options: Options) Self {
    return .{
        .offset = options.offset,
        .entries = options.entries,
    };
}

pub fn validateEntries(entries: anytype) ValidateError!void {
    var has_app = false;
    for (entries) |entry| {
        switch (entry.kind) {
            .app => {
                if (!isValidAppSubtype(entry.subtype)) return error.InvalidAppPartitionSubtype;
                has_app = true;
            },
            .data => {
                if (!isValidDataSubtype(entry.subtype)) return error.InvalidDataPartitionSubtype;
            },
        }
    }
    if (!has_app) return error.MissingAppPartition;
}

pub fn renderCsv(allocator: std.mem.Allocator, entries: anytype) std.mem.Allocator.Error![]u8 {
    var out = std.array_list.Managed(u8).init(allocator);
    errdefer out.deinit();

    const writer = out.writer();
    try writer.writeAll(
        "# AUTO-GENERATED BY ESPZ PARTITION GENERATOR\n" ++
            "# Name, Type, SubType, Offset, Size, Flags\n",
    );

    for (entries) |entry| {
        const flags = entry.flags orelse "";
        const subtype = try subtypeTextAlloc(allocator, entry.subtype);
        defer allocator.free(subtype);
        const offset = try formatOptionalHexAlloc(allocator, entry.offset);
        defer allocator.free(offset);
        const size = try formatHexAlloc(allocator, entry.size);
        defer allocator.free(size);
        try writer.print(
            "{s}, {s}, {s}, {s}, {s}, {s}\n",
            .{
                entry.name,
                typeText(entry.kind),
                subtype,
                offset,
                size,
                flags,
            },
        );
    }

    return out.toOwnedSlice();
}

pub fn resolveEntriesAlloc(allocator: std.mem.Allocator, table: Self) ![]ResolvedPartition {
    const resolved = try allocator.alloc(ResolvedPartition, table.entries.len);
    var next_offset = alignToSector(table.offset + partitionTableReservedSize());

    for (table.entries, 0..) |entry, idx| {
        const resolved_offset = entry.offset orelse next_offset;
        resolved[idx] = .{
            .name = entry.name,
            .kind = entry.kind,
            .subtype = entry.subtype,
            .offset = resolved_offset,
            .size = entry.size,
            .flags = entry.flags,
            .data = entry.data,
        };
        next_offset = alignToSector(resolved_offset + entry.size);
    }

    return resolved;
}

pub fn formatHexAlloc(allocator: std.mem.Allocator, value: u32) std.mem.Allocator.Error![]u8 {
    return std.fmt.allocPrint(allocator, "0x{x}", .{value});
}

pub fn formatOptionalHexAlloc(allocator: std.mem.Allocator, value: ?u32) std.mem.Allocator.Error![]u8 {
    if (value) |v| return formatHexAlloc(allocator, v);
    return allocator.dupe(u8, "");
}

pub fn subtypeTextAlloc(allocator: std.mem.Allocator, subtype: PartitionSubtype) std.mem.Allocator.Error![]u8 {
    return switch (subtype) {
        .factory => allocator.dupe(u8, "factory"),
        .ota => allocator.dupe(u8, "ota"),
        .ota_0 => allocator.dupe(u8, "ota_0"),
        .ota_1 => allocator.dupe(u8, "ota_1"),
        .phy => allocator.dupe(u8, "phy"),
        .nvs => allocator.dupe(u8, "nvs"),
        .spiffs => allocator.dupe(u8, "spiffs"),
        .littlefs => allocator.dupe(u8, "littlefs"),
        .device_profile => allocator.dupe(u8, "0x40"),
        .custom_name => |name| allocator.dupe(u8, name),
        .custom_value => |value| std.fmt.allocPrint(allocator, "0x{x}", .{value}),
    };
}

pub fn nvsCsvAlloc(allocator: std.mem.Allocator, entries: []const NvsEntry) ![]u8 {
    var out = std.array_list.Managed(u8).init(allocator);
    errdefer out.deinit();

    const writer = out.writer();
    try writer.writeAll("key,type,encoding,value\n");

    var current_namespace: ?[]const u8 = null;
    for (entries) |entry| {
        if (current_namespace == null or !std.mem.eql(u8, current_namespace.?, entry.namespace)) {
            current_namespace = entry.namespace;
            try writer.print("{s},namespace,,\n", .{entry.namespace});
        }
        const value_text = try nvsValueTextAlloc(allocator, entry.value);
        defer allocator.free(value_text);
        try writer.print(
            "{s},data,{s},{s}\n",
            .{
                entry.key,
                nvsEncodingText(entry.value_type),
                value_text,
            },
        );
    }

    return out.toOwnedSlice();
}

fn isValidAppSubtype(subtype: PartitionSubtype) bool {
    return switch (subtype) {
        .factory,
        .ota,
        .ota_0,
        .ota_1,
        .custom_name,
        .custom_value,
        => true,
        else => false,
    };
}

fn isValidDataSubtype(subtype: PartitionSubtype) bool {
    return switch (subtype) {
        .ota,
        .phy,
        .nvs,
        .spiffs,
        .littlefs,
        .device_profile,
        .custom_name,
        .custom_value,
        => true,
        else => false,
    };
}

fn typeText(kind: PartitionType) []const u8 {
    return switch (kind) {
        .app => "app",
        .data => "data",
    };
}

fn partitionTableReservedSize() u32 {
    return 0x1000;
}

fn alignToSector(value: u32) u32 {
    return (value + 0xfff) & ~@as(u32, 0xfff);
}

fn nvsEncodingText(value_type: NvsValueType) []const u8 {
    return switch (value_type) {
        .u8 => "u8",
        .i8 => "i8",
        .u16 => "u16",
        .i16 => "i16",
        .u32 => "u32",
        .i32 => "i32",
        .u64 => "u64",
        .i64 => "i64",
        .string => "string",
        .blob => "binary",
    };
}

fn nvsValueTextAlloc(allocator: std.mem.Allocator, value: NvsValue) std.mem.Allocator.Error![]u8 {
    return switch (value) {
        .signed => |v| std.fmt.allocPrint(allocator, "{d}", .{v}),
        .unsigned => |v| std.fmt.allocPrint(allocator, "{d}", .{v}),
        .str => |v| allocator.dupe(u8, v),
        .blob => |v| allocator.dupe(u8, v),
    };
}

test "default partition includes factory app" {
    try validateEntries(default_table.entries);
}

test "ota app partitions are valid" {
    const entries = [_]ResolvedPartition{
        .{
            .name = "ota_0",
            .kind = .app,
            .subtype = .ota_0,
            .offset = 0x10000,
            .size = 0x100000,
        },
    };
    try validateEntries(entries);
}

test "ota data partition is valid" {
    const entries = [_]ResolvedPartition{
        .{
            .name = "factory",
            .kind = .app,
            .subtype = .factory,
            .offset = 0x10000,
            .size = 0x100000,
        },
        .{
            .name = "otadata",
            .kind = .data,
            .subtype = .ota,
            .offset = 0x9000,
            .size = 0x2000,
        },
    };
    try validateEntries(entries);
}

test "invalid app subtype is rejected" {
    const entries = [_]ResolvedPartition{
        .{
            .name = "bad-app",
            .kind = .app,
            .subtype = .nvs,
            .offset = 0x10000,
            .size = 0x100000,
        },
    };
    try std.testing.expectError(error.InvalidAppPartitionSubtype, validateEntries(entries));
}
