const std = @import("std");

pub const Value = union(enum) {
    bool: bool,
    string: []const u8,
    integer: i64,
    raw: []const u8,

    pub fn eql(lhs: Value, rhs: Value) bool {
        const lhs_tag = std.meta.activeTag(lhs);
        const rhs_tag = std.meta.activeTag(rhs);
        if (lhs_tag != rhs_tag) return false;

        return switch (lhs) {
            .bool => |value| value == rhs.bool,
            .string => |value| std.mem.eql(u8, value, rhs.string),
            .integer => |value| value == rhs.integer,
            .raw => |value| std.mem.eql(u8, value, rhs.raw),
        };
    }
};

pub const Entry = struct {
    key: []const u8,
    value: Value,

    pub fn flag(key: []const u8, enabled: bool) Entry {
        return .{
            .key = key,
            .value = .{ .bool = enabled },
        };
    }

    pub fn str(key: []const u8, text: []const u8) Entry {
        return .{
            .key = key,
            .value = .{ .string = text },
        };
    }

    pub fn int(key: []const u8, number: i64) Entry {
        return .{
            .key = key,
            .value = .{ .integer = number },
        };
    }

    pub fn raw(key: []const u8, text: []const u8) Entry {
        return .{
            .key = key,
            .value = .{ .raw = text },
        };
    }

    pub fn eql(lhs: Entry, rhs: Entry) bool {
        return std.mem.eql(u8, lhs.key, rhs.key) and lhs.value.eql(rhs.value);
    }
};

pub const ModuleDoc = struct {
    name: []const u8,
    entries: []const Entry,
};

pub const RenderError = error{ConfigKeyConflict};

pub const RawValue = struct {
    text: []const u8,
};

pub fn raw(comptime text: []const u8) RawValue {
    return .{ .text = text };
}

pub fn make(comptime macros: anytype) @TypeOf(macros) {
    validateMacroSet(@TypeOf(macros), "esp_idf.SdkConfig.make() input");
    return macros;
}

pub fn render(
    allocator: std.mem.Allocator,
    modules: []const ModuleDoc,
) (std.mem.Allocator.Error || RenderError)![]u8 {
    var out: std.ArrayList(u8) = .empty;
    errdefer out.deinit(allocator);

    var seen = std.StringHashMap(Entry).init(allocator);
    defer seen.deinit();

    const writer = out.writer(allocator);
    try writer.writeAll(
        "# AUTO-GENERATED BY ESPZ SDKCONFIG AGGREGATOR\n" ++
            "# edit sdk_config in build_config.zig; do not edit this file manually\n\n",
    );

    for (modules) |module| {
        try writer.print("# [{s}]\n", .{module.name});

        for (module.entries) |entry| {
            if (seen.get(entry.key)) |existing| {
                if (!existing.eql(entry)) return error.ConfigKeyConflict;
                continue;
            }

            try seen.put(entry.key, entry);
            try writeEntry(writer, entry);
            try writer.writeByte('\n');
        }

        try writer.writeByte('\n');
    }

    return out.toOwnedSlice(allocator);
}

pub fn validateMacroSet(comptime MacroSet: type, comptime label: []const u8) void {
    switch (@typeInfo(MacroSet)) {
        .@"struct" => |struct_info| {
            inline for (struct_info.fields) |field| {
                validateMacroName(field.name);
                validateValueType(field.type, field.name);
            }
        },
        else => @compileError(std.fmt.comptimePrint(
            "{s} must be a struct literal, found {s}",
            .{ label, @typeName(MacroSet) },
        )),
    }
}

fn writeEntry(writer: anytype, entry: Entry) !void {
    switch (entry.value) {
        .bool => |enabled| {
            if (enabled) {
                try writer.print("{s}=y", .{entry.key});
            } else {
                try writer.print("# {s} is not set", .{entry.key});
            }
        },
        .string => |text| {
            try writer.print("{s}=", .{entry.key});
            try writeQuotedString(writer, text);
        },
        .integer => |number| {
            try writer.print("{s}={d}", .{ entry.key, number });
        },
        .raw => |text| {
            try writer.print("{s}={s}", .{ entry.key, text });
        },
    }
}

fn writeQuotedString(writer: anytype, text: []const u8) !void {
    try writer.writeByte('"');
    for (text) |c| {
        switch (c) {
            '"' => try writer.writeAll("\\\""),
            '\\' => try writer.writeAll("\\\\"),
            else => try writer.writeByte(c),
        }
    }
    try writer.writeByte('"');
}

test "render prints enabled/disabled/string/integer/raw entries" {
    const docs = [_]ModuleDoc{
        .{
            .name = "core",
            .entries = &.{
                Entry.flag("CONFIG_A", true),
                Entry.flag("CONFIG_B", false),
                Entry.str("CONFIG_C", "hello"),
                Entry.int("CONFIG_D", 42),
                Entry.raw("CONFIG_E", "0x8000"),
            },
        },
    };

    const rendered = try render(std.testing.allocator, &docs);
    defer std.testing.allocator.free(rendered);

    try std.testing.expect(std.mem.indexOf(u8, rendered, "CONFIG_A=y") != null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "# CONFIG_B is not set") != null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "CONFIG_C=\"hello\"") != null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "CONFIG_D=42") != null);
    try std.testing.expect(std.mem.indexOf(u8, rendered, "CONFIG_E=0x8000") != null);
}

test "render rejects conflicting values on same key" {
    const docs = [_]ModuleDoc{
        .{
            .name = "core",
            .entries = &.{Entry.flag("CONFIG_DUP", true)},
        },
        .{
            .name = "freertos",
            .entries = &.{Entry.flag("CONFIG_DUP", false)},
        },
    };

    try std.testing.expectError(
        error.ConfigKeyConflict,
        render(std.testing.allocator, &docs),
    );
}

test "render deduplicates repeated same key and value" {
    const docs = [_]ModuleDoc{
        .{
            .name = "core",
            .entries = &.{Entry.flag("CONFIG_SAME", true)},
        },
        .{
            .name = "alias",
            .entries = &.{Entry.flag("CONFIG_SAME", true)},
        },
    };

    const rendered = try render(std.testing.allocator, &docs);
    defer std.testing.allocator.free(rendered);

    try std.testing.expectEqual(@as(usize, 1), std.mem.count(u8, rendered, "CONFIG_SAME=y"));
}

pub fn validateMacroName(comptime name: []const u8) void {
    if (name.len == 0) {
        @compileError("sdkconfig macro names must not be empty");
    }
    if (std.mem.startsWith(u8, name, "CONFIG_")) {
        @compileError(std.fmt.comptimePrint(
            "sdkconfig macro '{s}' must omit the CONFIG_ prefix",
            .{name},
        ));
    }
    for (name) |c| {
        if (!((c >= 'A' and c <= 'Z') or (c >= '0' and c <= '9') or c == '_')) {
            @compileError(std.fmt.comptimePrint(
                "sdkconfig macro '{s}' must use only A-Z, 0-9, and '_'",
                .{name},
            ));
        }
    }
}

pub fn validateValueType(comptime ValueType: type, comptime name: []const u8) void {
    if (ValueType == RawValue) return;

    const info = @typeInfo(ValueType);
    switch (info) {
        .bool,
        .int,
        .comptime_int,
        .@"enum",
        .enum_literal,
        => {},
        .pointer => |ptr| {
            if (ptr.size == .slice and ptr.child == u8) return;
            if (ptr.size == .one) {
                switch (@typeInfo(ptr.child)) {
                    .array => |array| if (array.child == u8) return,
                    else => {},
                }
            }
            @compileError(std.fmt.comptimePrint(
                "sdkconfig macro '{s}' has unsupported pointer value type {s}",
                .{ name, @typeName(ValueType) },
            ));
        },
        .array => |array| {
            if (array.child == u8) return;
            @compileError(std.fmt.comptimePrint(
                "sdkconfig macro '{s}' has unsupported array value type {s}",
                .{ name, @typeName(ValueType) },
            ));
        },
        else => @compileError(std.fmt.comptimePrint(
            "sdkconfig macro '{s}' has unsupported value type {s}",
            .{ name, @typeName(ValueType) },
        )),
    }
}
