const esp_idf = @import("esp").idf;
const esp32s3_common = @import("esp32s3_boards_common");

pub const chip = "esp32s3";

pub const partition_table = esp_idf.PartitionTable.make(.{
    .entries = &.{
        .{
            .name = "nvs",
            .kind = .data,
            .subtype = .nvs,
            .size = 0x6000,
            .data = esp_idf.PartitionTable.data.nvs(.{}),
        },
        .{
            .name = "phy_init",
            .kind = .data,
            .subtype = .phy,
            .size = 0x1000,
        },
        .{
            .name = "factory",
            .kind = .app,
            .subtype = .factory,
            .size = 0x300000,
        },
    },
});

pub const task_policy = esp32s3_common.task_policy;

pub const sdk_config = esp_idf.SdkConfig.make(.{
    .ESPTOOLPY_FLASHSIZE = "16MB",
    .ESPTOOLPY_FLASHSIZE_16MB = true,
    .ESPTOOLPY_FLASHSIZE_2MB = false,
    .ESP_DEFAULT_CPU_FREQ_MHZ_160 = false,
    .ESP_DEFAULT_CPU_FREQ_MHZ_240 = true,
    .ESP_DEFAULT_CPU_FREQ_MHZ = 240,
    .ESP_CONSOLE_UART_DEFAULT = false,
    .ESP_CONSOLE_USB_SERIAL_JTAG = true,
    .ESP_CONSOLE_USB_SERIAL_JTAG_ENABLED = true,
    .ESP_CONSOLE_UART = false,
    .ESP_WIFI_ENABLED = true,
    .ESP_WIFI_NVS_ENABLED = true,
    .BT_ENABLED = true,
    .BT_CONTROLLER_ENABLED = true,
    .BT_CONTROLLER_ONLY = true,
    .BT_BLUEDROID_ENABLED = false,
    .BT_NIMBLE_ENABLED = false,
    .BTDM_CTRL_MODE_BLE_ONLY = true,
    .ESP_MAIN_TASK_STACK_SIZE = 24 * 1024,
    .SPIRAM = true,
    .SPIRAM_MODE_QUAD = false,
    .SPIRAM_MODE_OCT = true,
    .SPIRAM_SPEED_40M = false,
    .SPIRAM_SPEED_80M = true,
    .SPIRAM_USE_CAPS_ALLOC = true,
    .SPIRAM_USE_MALLOC = false,
    .SPIRAM_TRY_ALLOCATE_WIFI_LWIP = true,
    .ESP_WIFI_STATIC_RX_BUFFER_NUM = 16,
    .ESP_WIFI_DYNAMIC_RX_BUFFER_NUM = 64,
    .ESP_WIFI_STATIC_TX_BUFFER = true,
    .ESP_WIFI_DYNAMIC_TX_BUFFER = false,
    .ESP_WIFI_STATIC_TX_BUFFER_NUM = esp32s3_common.wifi.static_tx_buffer_num,
    .ESP_WIFI_CACHE_TX_BUFFER_NUM = esp32s3_common.wifi.cache_tx_buffer_num,
    .ESP_WIFI_AMPDU_TX_ENABLED = true,
    .ESP_WIFI_TX_BA_WIN = 32,
    .ESP_WIFI_AMPDU_RX_ENABLED = true,
    .ESP_WIFI_RX_BA_WIN = 10,
    .ESP_WIFI_TASK_PINNED_TO_CORE_0 = true,
    .ESP_WIFI_TASK_PINNED_TO_CORE_1 = false,
    .LWIP_TCPIP_TASK_AFFINITY_NO_AFFINITY = esp32s3_common.lwip.tcpip_task_affinity_no_affinity,
    .LWIP_TCPIP_TASK_AFFINITY_CPU0 = esp32s3_common.lwip.tcpip_task_affinity_cpu0,
    .LWIP_TCPIP_TASK_AFFINITY_CPU1 = esp32s3_common.lwip.tcpip_task_affinity_cpu1,
    .LWIP_TCP_SND_BUF_DEFAULT = 32 * 1440,
    .LWIP_TCP_WND_DEFAULT = 32 * 1440,
    .LWIP_TCP_RECVMBOX_SIZE = 48,
    .LWIP_UDP_RECVMBOX_SIZE = 48,
    .FREERTOS_HZ = 1000,
    .FREERTOS_USE_TRACE_FACILITY = true,
    .FREERTOS_GENERATE_RUN_TIME_STATS = true,
    .FREERTOS_RUN_TIME_COUNTER_TYPE_U32 = false,
    .FREERTOS_RUN_TIME_COUNTER_TYPE_U64 = true,
    .FREERTOS_RUN_TIME_STATS_USING_ESP_TIMER = true,
    .FREERTOS_RUN_TIME_STATS_USING_CPU_CLK = false,
});
