name: CI

concurrency:
  group: ci-${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - synchronize

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - if: matrix.os == 'ubuntu-24.04'
        run: zig build --seed 0
      - if: matrix.os != 'ubuntu-24.04'
        run: zig build

  unit:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-latest, windows-latest]
        optimize: [Debug, ReleaseSafe, ReleaseFast]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: Run unit tests
        if: matrix.os == 'ubuntu-24.04'
        run: zig build test-unit -Doptimize=${{ matrix.optimize }} --seed 0 --summary all
      - name: Run unit tests
        if: matrix.os != 'ubuntu-24.04'
        run: zig build test-unit -Doptimize=${{ matrix.optimize }} --summary all

  integration:
    needs: unit
    strategy:
      matrix:
        os: [ubuntu-24.04, ubuntu-24.04-arm, macos-latest, windows-latest]
        optimize: [Debug, ReleaseSafe, ReleaseFast]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v2
        with:
          version: 0.15.2
      - name: Run integration tests
        if: matrix.os == 'ubuntu-24.04'
        run: zig build test-integration -Doptimize=${{ matrix.optimize }} --seed 0 --summary all
      - name: Run integration tests
        if: matrix.os != 'ubuntu-24.04'
        run: zig build test-integration -Doptimize=${{ matrix.optimize }} --summary all
